version: '3.8'

# run with docker compose -f . run --rm terraform <command>

services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/terraform
    working_dir: /terraform
    env_file:
      - .env
